name: Cron Bump kube-tools Versions

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies and run job
      run: |
        cd .github/automation
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python main.py
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}