name: Lint

on: [push]

jobs:

  lint:

    name: hadolint

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: hadolint
      uses: hadolint/hadolint-action@v1.5.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HADOLINT_ACTION_DOCKERFILE_FOLDER: .
      with:
        ignore: 'DL3018'